package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/ricktimmis/mhclub/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Facility)
// DB Table: Plural (facilities)
// Resource: Plural (Facilities)
// Path: Plural (/facilities)
// View Template Folder: Plural (/templates/facilities/)

// FacilitiesResource is the resource for the Facility model
type FacilitiesResource struct {
	buffalo.Resource
}

// List gets all Facilities. This function is mapped to the path
// GET /facilities
func (v FacilitiesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	facilities := &models.Facilities{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Facilities from the DB
	if err := q.All(facilities); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, facilities))
}

// Show gets the data for one Facility. This function is mapped to
// the path GET /facilities/{facility_id}
func (v FacilitiesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Facility
	facility := &models.Facility{}

	// To find the Facility the parameter facility_id is used.
	if err := tx.Find(facility, c.Param("facility_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, facility))
}

// New renders the form for creating a new Facility.
// This function is mapped to the path GET /facilities/new
func (v FacilitiesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Facility{}))
}

// Create adds a Facility to the DB. This function is mapped to the
// path POST /facilities
func (v FacilitiesResource) Create(c buffalo.Context) error {
	// Allocate an empty Facility
	facility := &models.Facility{}

	// Bind facility to the html form elements
	if err := c.Bind(facility); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(facility)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, facility))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Facility was created successfully")

	// and redirect to the facilities index page
	return c.Render(201, r.Auto(c, facility))
}

// Edit renders a edit form for a Facility. This function is
// mapped to the path GET /facilities/{facility_id}/edit
func (v FacilitiesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Facility
	facility := &models.Facility{}

	if err := tx.Find(facility, c.Param("facility_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, facility))
}

// Update changes a Facility in the DB. This function is mapped to
// the path PUT /facilities/{facility_id}
func (v FacilitiesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Facility
	facility := &models.Facility{}

	if err := tx.Find(facility, c.Param("facility_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Facility to the html form elements
	if err := c.Bind(facility); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(facility)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, facility))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Facility was updated successfully")

	// and redirect to the facilities index page
	return c.Render(200, r.Auto(c, facility))
}

// Destroy deletes a Facility from the DB. This function is mapped
// to the path DELETE /facilities/{facility_id}
func (v FacilitiesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Facility
	facility := &models.Facility{}

	// To find the Facility the parameter facility_id is used.
	if err := tx.Find(facility, c.Param("facility_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(facility); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Facility was destroyed successfully")

	// Redirect to the facilities index page
	return c.Render(200, r.Auto(c, facility))
}
